export const appConstants = {
  // MAP KEYS
  data: "data",
  type: "type",
  class_data: "user_data",
  enable_loader: "enable_loader",
  error_message: "error_message",
  exception_object: "exception_object",
  job_create_data: "job_create_data",
  create_profile_data: "create_profile_data",
  show_accept_button: "show_accept_button",
  user_data: "user",
  token_data: "token",
  apns_data: "apns",
  is_toast: "isToast",
  device_token: "device_token",
  on_subscribe_navigate_to: "on_subscribe_navigate_to",
  unread_notification_count: "unread_notification_count",
  notification_type: "notification_type",
  unread_messages: "unread_messages",
  pin: "pin",
  call_state: "call_state",
  call_data: "call_data",
  boost_job_id: "boost_job_id",
  call_duration: "call_duration",
  max_amount: 2147483647,
  chatId: "chatId",
  update: "update",
  root: "root",
  update_data: "data",
  caller: "userData",
  media_loader : "mediaLoader"

};
