import { StyleSheet } from "react-native";
import { colors } from "./constants/colors";
import { dimensConstants } from "./constants/dimensConstant";
import { fontSize, fonts } from "./constants/fonts";

export const globalStyles = StyleSheet.create({
  flex1: {
    flex: 1,
  },
  flex1WithBackground: {
    flex: 1,
    backgroundColor: colors.primary_background_color,
  },
  safeAreaViewStyle: {
    flex: 1,
    backgroundColor: colors.primary_background_color,
    paddingBottom: dimensConstants.standard.padding,
  },
  headerWrapper: {
    width: "100%",
    height: 60,
    backgroundColor: colors.secondary_background_color,
    flexDirection: "row",
  },
  headerTitle: {
    marginHorizontal: 60,
    fontSize: fontSize.header_title_size,
    fontFamily: fonts.primary_regular_font,
    color: colors.title_text_theme,
    flex: 1,
    textAlign: "center",
    alignSelf: "center",
  },
  appInputContainer: {
    alignSelf: "center",
    width: "100%",
    backgroundColor: colors.primary_background_color,
  },
  inputWrapper: {
    flexDirection: "row",
    width: "100%",
    position: "relative",
    borderColor: colors.secondary_theme,
    borderWidth: dimensConstants.app_input.border.width,
    borderRadius: dimensConstants.app_input.border.radius,
  },
  input: {
    fontSize: fontSize.input_content_size,
    padding: 15,
    flex: 1,
    color: colors.input_content,
    includeFontPadding: false,
  },
  inputError: {
    fontSize: fontSize.input_error_size,
    marginTop: dimensConstants.standard.margin_horizontal,
    color: colors.input_error,
    alignSelf: "center",
    includeFontPadding: false,
  },
  iconStyle: {
    minHeight: dimensConstants.app_image_icon.height,
    minWidth: dimensConstants.app_image_icon.width,
    alignSelf: "center",
  },
  iconWrapper: {
    justifyContent: "center",
    alignItems: "center",
    alignContent: "center",
    padding: 10,
  },
  standardButtonWrapper: {
    borderRadius: 10,
    minHeight: 45,
    justifyContent: "center",
  },
  standardButton: {
    borderRadius: dimensConstants.border_radius,
    minHeight: dimensConstants.button_height,
    justifyContent: "center",
    backgroundColor: colors.primary_action_button_background_theme,
    marginHorizontal: dimensConstants.standard.margin_horizontal,
    marginVertical: dimensConstants.standard.margin_vertical,
  },
  standardButtonText: {
    color: colors.primary_action_text_theme,
    fontFamily: fonts.primary_regular_font,
    fontSize: fontSize.subtitle_size,
    justifyContent: "center",
    alignSelf: "center",
    textAlign: "center",
    textTransform: "uppercase",
  },
  standardMarginVertical: {
    marginVertical: 10,
  },
  standardMarginHorizontal: {
    marginHorizontal: dimensConstants.standard.margin_horizontal,
  },
  title: {
    fontSize: fontSize.title_size,
    fontFamily: fonts.primary_semi_bold_font,
    color: colors.title_color,
  },
  actionTitle: {
    fontSize: fontSize.title_size,
    fontFamily: fonts.primary_semi_bold_font,
    color: colors.primary_action_text_theme,
  },
  subtitle: {
    fontSize: fontSize.subtitle_size,
    fontFamily: fonts.primary_semi_bold_font,
    color: colors.subtitle_text_theme,
  },
  onBoardingText: {
    fontFamily: fonts.primary_regular_font,
    fontSize: 16,
    lineHeight: 21,
    color: colors.text_color,
  },
  activeDotStyle: {
    width: 40,
    height: 8,
    borderRadius: 10,
  },
  dotStyle: {
    opacity: 0.4,
  },
  RCC: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  RSBC: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginLeft: 8,
    backgroundColor: colors.dot_background,
  },
  draggableViewStyle: {
    width: 50,
    height: 5,
    borderRadius: 4,
    backgroundColor: colors.secondary_action_text_theme,
    alignSelf: "center",
    marginVertical: dimensConstants.standard.margin_horizontal,
  },
  emptyView: {
    height: dimensConstants.button_height,
  },
  centerParent: {
    justifyContent: "center",
    alignItems: "center",
  },
  btnText: {
    fontFamily: fonts.primary_bold_font,
    fontSize: 12,
    lineHeight: 13,
    textAlign: "center",
    color: colors.title_color,
  },
  screenTitleStyle1: {
    fontFamily: fonts.primary_bold_font,
    fontSize: 16,
    lineHeight: 18,
    color: colors.text_dark,
  },
  wh100: {
    width: "100%",
    height: "100%",
    overflow: "hidden",
  },
  pickerListItemStyle: {
    justifyContent: "flex-start",
    flexDirection: "row",
    paddingHorizontal: 20,
    minHeight: 62,
    alignItems: "center",
    width: "100%",
    borderRadius: 10,
    marginVertical: 4,
    backgroundColor: colors.white,
  },
  modalTitle: {
    fontSize: 20,
    lineHeight: 34,
    color: colors.title_color,
    fontFamily: fonts.primary_bold_font,
    textAlign: "center",
  },
  modalDesc: {
    fontSize: 16,
    lineHeight: 24,
    color: colors.desc_color,
    fontFamily: fonts.primary_regular_font,
    marginHorizontal: 45,
    textAlign: "center",
    marginTop: 4,
  },
  pickerLabel: {
    fontFamily: fonts.primary_bold_font,
    fontSize: 16,
    lineHeight: 24,
    color: colors.title_color,
    marginLeft: 20,
  },
  pickerCancelButtonStyle: {
    fontFamily: fonts.primary_regular_font,
    color: colors.desc_color,
    fontSize: 14,
    lineHeight: 24,
    textAlign: "center",
    marginTop: 26,
    marginBottom: 30,
  },
  title_20: {
    fontFamily: fonts.primary_semi_bold_font,
    fontSize: 20,
    lineHeight: 24,
    color: colors.title_color,
    textAlign: "center",
  },
  desc_16: {
    fontFamily: fonts.primary_regular_font,
    fontSize: 16,
    lineHeight: 20,
    color: colors.subheading_color,
    textAlign: "center",
  },
  tipText: {
    fontFamily: fonts.primary_regular_font,
    fontSize: 14,
    color: colors.rockt_orange,
    lineHeight: 24,
    textAlign: "center",
    marginLeft: 10,
    padding: 8,
    marginTop: -2,
  },
  multiImagesBottomText: {
    fontSize: 14,
    lineHeight: 24,
    color: colors.desc_color,
    fontFamily: fonts.primary_regular_font,
    marginTop: 16,
    textAlign: "center",
    marginBottom: 25,
  },
  leftAction: {
    start: 0,
    position: "absolute",
    alignSelf: "flex-start",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 26,
  },
  rightAction: {
    end: 0,
    position: "absolute",
    alignSelf: "flex-start",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 24,
  },
  circularIcon: {
    height: 44,
    width: 44,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: colors.gray6,
    marginRight: 12,
    justifyContent: "center",
    alignItems: "center",
  },
  noteStyle: {
    fontFamily: fonts.primary_regular_font,
    fontSize: 14,
    lineHeight: 20,
    color: colors.desc_color,
    textAlign: "center",
    marginVertical: 24,
  },
});
